spring:
  profiles:
    active: dev
debug: true
appname: bc-service

---
spring:
  profiles: dev
server:
  port: 8101
logging:
  path: logs
  config: classpath:logback-spring.xml
jdbc:
  url: jdbc:mysql://127.0.0.1:3306/cp_buss?characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
  username: root
  password: YJtjmGSGY129I9npNp8sh0GirIhbhNs21rwDL36v0Cu4KIzpZJWsHVNSIMe20/UuX9BValKAGxEcNwkswYxmEA==
  url1: jdbc:mysql://127.0.0.1:3306/cp_buss?characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
  username1: root
  password1: YJtjmGSGY129I9npNp8sh0GirIhbhNs21rwDL36v0Cu4KIzpZJWsHVNSIMe20/UuX9BValKAGxEcNwkswYxmEA==
commonQuery_gateway: http://127.0.0.1:8107/commonQuery/

---
spring:
  profiles: prod
server:
  port: 8001
logging:
  path: /home/ubuntu/logs
  config: classpath:logback-spring.xml
jdbc:
  url: jdbc:mysql://cd-cdb-7cb7r7d2.sql.tencentcdb.com:63812/cp_buss?characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
  username: root
  password: FGq2PNXG5qJr6AdgX6naidjMG2qUX9l3vtmWmUj5yDnIDV+tDwwG278zUw7E1dYQvIku8fgPcmjFHovQI8KiEA==
  url1: jdbc:mysql://cd-cdb-7cb7r7d2.sql.tencentcdb.com:63812/cp_buss?characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
  username1: root
  password1: FGq2PNXG5qJr6AdgX6naidjMG2qUX9l3vtmWmUj5yDnIDV+tDwwG278zUw7E1dYQvIku8fgPcmjFHovQI8KiEA==
commonQuery_gateway: http://127.0.0.1:8007/commonQuery/


